# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companylisting', '0002_auto_20160303_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_estimated_earnings',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
